In [3]:
import numpy as np
hello = 'Hello World'
print(hello)

Hello World


In [4]:
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [5]:
arr2 = np.array([1,2;12,2])

SyntaxError: invalid syntax (<ipython-input-5-018aa6bed486>, line 1)

In [6]:
arr2 = np.array([1,212,2])

In [7]:
arr2 = np.array([1,2])

In [8]:
arr2 = np.array([1,3] [3,4])

TypeError: list indices must be integers or slices, not tuple

In [9]:
arr2 = np.array([1,2],[3,4])

TypeError: data type not understood

In [11]:
arr2 = np.array[[[1,2],[3,4]]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [12]:
arr3 = np.array([1,2,3,4,5,6],ndmin=3)
print(arr3)

[[[1 2 3 4 5 6]]]


In [13]:
arr_float = np.array(arr3, dtype=float)
print(arr_float)

[[[1. 2. 3. 4. 5. 6.]]]


In [14]:
arr_bool = np.array([0,1,0,1], dtype=bool)
print(arr_bool)

[False  True False  True]


In [15]:
print(arr3)
print(arr3.shape)

[[[1 2 3 4 5 6]]]
(1, 1, 6)


In [16]:
#resize an array using the .shape attribute
arr4 = np.array(arr2)
print(arr4)
print(arr4.shape)

arr4.shape = (4,1)
print(arr4)
print(arr4.shape)

[[1 2]
 [3 4]]
(2, 2)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [17]:
arr5 = arr2.reshape(4,1)
print(arr5)

[[1]
 [2]
 [3]
 [4]]


In [19]:
arr5=np.arrange(1)
array([1,20])

AttributeError: module 'numpy' has no attribute 'arrange'

In [30]:
x=np.arange(21)
print(x)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [36]:
y=np.linspace(1,20,20)
print(y)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


In [38]:
xnum_arr=np.asarray(4)
print(xnum_arr)

4


In [45]:
a = np.arange(5,30,2)
print(a)
print(a[:5])
print(a[2:5])
print(a[7:])
print(a[::-1])


[ 5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 5  7  9 11 13]
[ 9 11 13]
[19 21 23 25 27 29]
[29 27 25 23 21 19 17 15 13 11  9  7  5]


In [46]:
m = np.array([9,18,27,36])
n = np.array([10,20,30,40])
o = np.array([7,14,21,28])

print(m, '\n', n,'\n',o)
print(np.concatenate([m,n]))
print(np.concatenate([m,n,o]))

[ 9 18 27 36] 
 [10 20 30 40] 
 [ 7 14 21 28]
[ 9 18 27 36 10 20 30 40]
[ 9 18 27 36 10 20 30 40  7 14 21 28]


In [47]:
r = np.arange(8)
print("r=",r)
print("r + 10=",r + 10)
print("r/2=",r/2)

r= [0 1 2 3 4 5 6 7]
r + 10= [10 11 12 13 14 15 16 17]
r/2= [0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [48]:
s = np.arange(100)

def div_by_2(array):
    v = np.empty(len(array))
    for i in range(len(array)):
        v(i) = i/2
    return v
r2 = div_by_2(r)
print(r2)

%timeit s2_numpy = s/2
print(len(s2_numpy))

%timeit s2_loop =div_by_2(s)
print(len(s2_loop))

SyntaxError: can't assign to function call (<ipython-input-48-75fe2e6e2850>, line 6)

In [49]:
X=np.random.random(1000)
print(np.sum(X))

498.6913692248298


In [60]:
y=np.random.randint(1,10,100)
print(y)                    
print("mean=", np.mean(y))
print("variance=", np.var(y))
print("standard deviation=", np.std(y))
print("median=", np.median(y))

[6 2 6 9 9 3 5 6 6 8 6 2 8 6 1 4 8 5 5 3 1 3 1 8 5 6 9 9 7 7 1 5 2 2 1 7 4
 6 5 8 6 1 6 5 6 9 8 4 3 9 2 4 2 4 7 3 8 7 1 7 9 4 1 7 7 5 5 7 4 3 4 2 4 2
 3 3 1 3 7 8 1 8 6 3 5 8 9 7 6 7 5 6 8 9 5 8 6 3 1 3]
mean= 5.1
variance= 6.189999999999998
standard deviation= 2.4879710609249455
median= 5.0
